name: KabanSMP
main: io.github.kabanfriends.kabansmp.KabanSMPPlugin
version: 1.1.1
author: KabanFriends
api-version: 1.20
depend: [ProtocolLib, Vault, floodgate]
load: STARTUP

commands:
  test:
    description: A test command
    usage: /test
    permission: 4
  reloadlang:
    description: Reloads language files
    usage: /reloadlang
    permission: 4
  pvp:
    description: Toggle PVP
    usage: /pvp
  sethome:
    description: Set the player's home location
    usage: /sethome
  home:
    description: Teleport to the player's home location
    usage: /home
  hardcore:
    description: Enables the hardcore mode
    usage: /hardcore
